services:
  - type: web
    name: gardi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn student_management_system.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: student_management_system.settings
      - key: SECRET_KEY
        value: 'so*rai_2(lk7t(yh%de+_kp_c%*r_b9wkga%gyo5tl9_8_r!xx'
      - key: DEBUG
        value: False
